name: orpo
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.9.25=he39995d_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py39hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses==0.6
      - dfa==2.1.2
      - distro==1.9.0
      - dm-tree==0.1.8
      - exceptiongroup==1.3.1
      - execnet==2.1.2
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - flow==0.5.0.dev0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - funcy==1.18
      - gymnasium==0.28.1
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - imutils==0.5.4
      - iniconfig==2.1.0
      - istype==0.2.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lazytree==0.3.2
      - lenses==0.5.0
      - lxml==6.0.2
      - lz4==4.4.5
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - numpy==2.0.2
      - openai==2.8.1
      - opencv-python==4.12.0.88
      - ordered-set==4.1.0
      - packaging==25.0
      - pandas==2.3.3
      - pandemic-simulator==1.1.0
      - pillow==11.3.0
      - pluggy==1.6.0
      - probabilistic-automata==0.4.2
      - protobuf==6.33.1
      - py==1.11.0
      - pyarrow==21.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyglet==2.1.11
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyrsistent==0.20.0
      - pytest==8.4.2
      - pytest-forked==1.6.0
      - pytest-xdist==2.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - ray==2.7.0
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.27.1
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shellingham==1.5.4
      - singledispatch==4.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - structlog==25.5.0
      - sumotools==0.3.1
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tomli==2.3.0
      - torch==2.8.0
      - tqdm==4.67.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/orpo
